module.exports = {
    schools: [
        {title: "Engineering", img: "../img/icons/engineering.png"},
        {title: "Arts", img: "../img/icons/arts.png"},
        {title: "Human Ecology", img: "../img/icons/human_ecology.png"},
        {title: "Hotel", img: "../img/icons/hotel.png"},
        {title: "CALS", img: "../img/icons/cals.png"},
        {title: "Architecture", img: "../img/icons/architecture.png"},
        {title: "Business", img: "../img/icons/business.png"},
        {title: "ILR", img: "../img/icons/ilr.png"},
    ],
    majors: [
        "Computer Science",
        "Hotel Things",
        "Economics",
        "Accounting",
        "Applied and Engineering Physics",
        "Art History",
        "Basket Weaving",
    ],
    minors: [
        "Computer Science",
        "Hotel Things",
        "Economics",
        "Accounting",
        "Applied and Engineering Physics",
        "Art History",
        "Basket Weaving",
    ],
    classesTaken: [
        "AEM 2540",
        "CS 4780",
        "ECE 3210",
        "MATH 2930",
    ],
    classesDesired: [
        "AEM 2540",
        "CS 4780",
        "ECE 3210",
        "MATH 2930",
    ],
    graduatingSemester: [
        "Spring 2017",
        "Fall 2017",
        "Spring 2018",
        "Fall 2018",
        "Spring 2019",
    ],
    keyCodes: {
        ESC: 27,
        UP: 38,
        DOWN: 40,
        ENTER: 13,
        TAB: 9,
    },
    semesterYears: [
        16,
        17,
        18,
        19,
    ],
}