module.exports = {
    schools: [
        {title: "Engineering", img: "http://www.kiawahisland.org/Data/Sites/1/media/biweekly-email-/007-512.png"},
        {title: "Arts", img: "http://squad.se/wp-content/uploads/2016/08/Hard-Money-Icon-3.png"},
        {title: "Human Ecology", img: "http://www.morethanprinting.co/images/educationIcon.png"},
        {title: "Hotel", img: "http://www.hotel-r.net/im/hotel/gb/icon-hotel-18.png"},
        {title: "CALS", img: "http://www.cals.nl/wp-content/themes/calscollegelocatie/assets/img/logo.svg"},
    ],
    majors: [
        "Computer Science",
        "Hotel Things",
        "Economics",
        "Accounting",
        "Applied and Engineering Physics",
        "Art History",
        "Basket Weaving",
    ],
    minors: [
        "Computer Science",
        "Hotel Things",
        "Economics",
        "Accounting",
        "Applied and Engineering Physics",
        "Art History",
        "Basket Weaving",
    ],
    classesTaken: [
        "AEM 2540",
        "CS 4780",
        "ECE 3210",
        "MATH 2930",
    ],
    classesDesired: [
        "AEM 2540",
        "CS 4780",
        "ECE 3210",
        "MATH 2930",
    ],
    graduatingSemester: [
        "Spring 2017",
        "Fall 2017",
        "Spring 2018",
        "Fall 2018",
        "Spring 2019",
    ],
    keyCodes: {
        ESC: 27,
        UP: 38,
        DOWN: 40,
        ENTER: 13,
    },
}